version: 2
jobs:
   build:
     machine: true
     steps:
       - checkout
       - run: |
            aws --region eu-west-1 ecr describe-repositories --registry-id 307921801440
            aws --region eu-west-1 ecr get-login
            curl -sS ifconfig.co
