version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.5
     steps:
       - checkout
       - run: |
            pwd
            echo
            ls -al
            echo
            ls -al ~/
            
