version: 2
jobs:
   build:
     machine: true
     steps:
       - checkout
       - run: |
            pwd
            echo
            ls -al
            echo
            ls -al ~/
            echo
            ls -al /
