version: 2
jobs:
   build:
     machine: true
     environment:
       - AWS_ACCOUNT: "307921801440"
       - ECR_ENDPOINT: "307921801440.dkr.ecr.eu-west-1.amazonaws.com/"
       - ECR_REPO_NS: "cms"
     steps:
       - checkout
       - run: |
            curl -sS -o ./docker-build/files/ec2-metadata http://s3.amazonaws.com/ec2metadata/ec2-metadata
            chmod 755 ./docker-build/files/ec2-metadata
            docker build -t ${ECR_REPO_NS}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_PREVIOUS_BUILD_NUM} \
              ./docker-build
            docker images -a
            echo
            echo "AWS_ACCOUNT: $AWS_ACCOUNT"
            echo "ECR_ENDPOINT: $ECR_ENDPOINT"
            echo
            $(aws --region eu-west-1 ecr get-login)
            docker tag ${ECR_REPO_NS}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_PREVIOUS_BUILD_NUM} \
              ${ECR_ENDPOINT}/${ECR_REPO_NS}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_PREVIOUS_BUILD_NUM}
            docker push ${ECR_ENDPOINT}/${ECR_REPO_NS}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_PREVIOUS_BUILD_NUM}


